[package]
name = "wasi-misc-tests"
version = "0.1.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[dependencies]
libc = "0.2.65"
wasi = "0.7.0"
more-asserts = "0.2.1"
