name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-wasi
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target wasm32-wasi
